version: '3.8'

volumes:
  postgres_data:
  backend_static:
  backend_media:
  frontend_build:

services:
  db:
    image: postgres:16-alpine
    container_name: foodgram_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: foodgram_frontend_builder
    volumes:
      - frontend_build:/app/build

  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: foodgram_backend
    restart: unless-stopped
    volumes:
      - backend_static:/app/static/
      - backend_media:/app/media/
    depends_on:
      - db
    env_file:
      - ../backend/.env

  nginx:
    image: nginx:1.25.4-alpine
    container_name: foodgram_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_build:/usr/share/nginx/html/frontend/:ro
      - backend_static:/usr/share/nginx/html/static/:ro
      - backend_media:/usr/share/nginx/html/media/:ro
      - ../docs/:/usr/share/nginx/html/api/docs/:ro
    depends_on:
      - backend
      - frontend